version: "3.2"

services:
  deformdemo:
    hostname: deformdemo
    build:
      context: .
    ports:
      - 8522:8522
  selenium:
    hostname: selenium
    image: selenium/standalone-firefox:4.0.0-alpha-7-prerelease-20200826
    ports:
      - 5900:5900 # for vnc debugging
      - 4444:4444
    environment:
      - VNC_PASSWORD=secret
      - SCREEN_WIDTH=1920
      - SCREEN_HEIGHT=1080
    volumes:
      - /dev/shm:/dev/shm
  tester:
    container_name: tester
    build:
      context: .
      dockerfile: Dockerfile-tests
    volumes:
      - .:/app:delegated
    depends_on:
      - deformdemo
      - selenium
    command: bash -c "tail -f /dev/null"
